### ISSUE TITLE
Service Activity reporting form and draft reporting form/question headings need wrapping 

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-reporting#107]
Wrap the questions and the headings on the service activity reporting forms and draft report for both English and Swahili because you cannot read them

**Comment by ellykits** [comment]
Resolved to change the design to below. The hint now extracted to a label therefore no longer needs wrapping.
![Screenshot_1599659137](https://user-images.githubusercontent.com/26865532/92614964-48147200-f2c5-11ea-8c34-4c149a37ca37.png)

**Comment by msschroeder** [comment]
Looks great! Good job!
