### ISSUE TITLE
Referrals are not syncing from the CHW to HF as expected

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-reporting#108]
Referrals are not syncing from CHW app issuing referral to the Health Facility

To replicate:
1. Open a profile
2. Open the refer to a health facility
3. Fill in the referral and send to the linked HF 
4. Open the HF the referral was sent to.

**Comment by manutarus** [comment]
@msschroeder are the users on the CHW app and the HF app mapped to the same team while using this feature ?

**Comment by msschroeder** [comment]
@manutarus Yes, they are users on the CHW app and HF app mapped to the same team. I tested a couple of times yesterday using the staging server and two accounts on a location with the correct tags and correct location levels.

**Comment by allan-allay** [comment]
Couldn't recreate the sync problem as described above

**Comment by Mstjamush** [comment]
Sync is not happening @allan-allay

**Comment by ellykits** [comment]
@msschroeder I tested with CHW user **chwone** and HF user **hfone** and the referrals sync are working as expected when you issue a referral to **Huruma** facility since the HF user is tied to that facility and is in the same team as CHW user.

**Comment by msschroeder** [comment]
@ellykits It is not working for the client and also not working for another account I created to try this. I can share these credentials if need be

**Comment by msschroeder** [comment]
Looks great! Good job!
