### ISSUE TITLE
Stock Usage Report time drop-down menu

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-reporting#52]
- [ ] The drop down menu will display the month and year of the current month and any previous months where this data is collected.
- [ ] The past months available include up to the last 12 months
- [ ] The current month and year will be at the top of the drop down and going in reverse chronological order for the last 12 months. For example, if today is February 2020 and I have used the app for the last 3 months (Jan, Dec 2019, Nov 2019). The drop down would be in the order: February 2020, January 2020, December 2019, November 2019
@manutarus @paulinembabu Will the translations work correctly in such a function?

**Comment by msschroeder** [comment]
QA Mar 4th:
- [ ] The drop down will display **the month and year of the current month** and any previous months where this data is collected. Currently, it is only showing the previous month. 

To replicate:
1. Today is March 4. The only values in the drop down are Feb 2019 to Mar 2018.

**Comment by manutarus** [comment]
@msschroeder Our understanding was this are monthly reports and the reports are calculated at the end of each month, for us to include the stock usage for the current month this would require a daily tally.

**Comment by msschroeder** [comment]
lgtm
