### ISSUE TITLE
Add stock usage report to the side panel

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-reporting#55]
- [x] Add the stock usage reporting
- [x] Title is 'Stock usage report'
- [x] It will appear below all the modules and above the language selection (as shown in the image below). It will appear in the same section as the language selection and log out.
- [x] Use the icon provided by @rowo 

![sidepannel](https://user-images.githubusercontent.com/20777928/74755249-f1413f80-5283-11ea-9d8b-42fc7f21d602.png)

**Comment by rowo** [comment]
I added the icon file here: https://drive.google.com/file/d/11_E-yxvqLHhgmSXhfB8wcOVoXnHZ2Zb7/view

**Comment by msschroeder** [comment]
lgtm
