### ISSUE TITLE
Add service activity to the side panel - CHW

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-reporting#63]
- [x] Add the service activity to the side panel
- [x] Title is 'Service activity'
- [x] It will appear below all the modules and above the language selection and stock usage (as shown in the image below). It will appear in the same section as the language selection and log out.
- [ ] Please use the icon on the left -  @rowo can you provide this icon

![image4](https://user-images.githubusercontent.com/20777928/75346484-de47f400-58af-11ea-8b0d-10eb2c2aece7.png)

**Comment by msschroeder** [comment]
@rowo  Would you mind providing the icon

**Comment by rowo** [comment]
@msschroeder @paulinembabu 
![icon-service-activity](https://user-images.githubusercontent.com/1584163/77352578-c7ad8500-6d15-11ea-8548-108c242bd97c.png)

**Comment by msschroeder** [comment]
lgtm
