### ISSUE TITLE
Generate the draft report submission confirmation- CHW

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-reporting#67]
- [ ] When I click CONFIRM at the bottom of the draft report, it will generate a message (shown in the figure below)
- [ ] The message has the following content:
- [ ] First row of text: Send the [Month Abbreviated] [Year] report?
- [ ] Second row of text: Date: [date on device]
- [ ] Third row of text: User: [username]
- [ ] The message choice option CANCEL will take you back to the previous screen
- [ ] The message choice option CANCEL will SEND send the report.

![image2](https://user-images.githubusercontent.com/20777928/75349701-59140d80-58b6-11ea-9b67-0609ac516977.png)

@manutarus @paulinembabu Currently, this process requires the user to have an internet connection to send. If they don't it goes back to draft reports. I was wondering what the LOE would be to change this to have it queue in the background once I hit submit and automatically submit when I get an internet connection?

**Comment by msschroeder** [comment]
QA March 18:
- [ ] The message choice option CANCEL will take you back to the previous screen. CANCEL does not take you back to the generated draft report

Replicate:
1. Generate a report
2. Move to the last page
3. Click CONFIRM
4. Hit Cancel
5. It saves as a draft and appears on the main Draft Report Tab

@manutarus @paulinembabu Currently, this process requires the user to have an internet connection to send. If they don't it goes back to draft reports. I was wondering what the LOE would be to change this to have it queue in the background once I hit submit and automatically submit when I get an internet connection?

**Comment by paulinembabu** [comment]
@msschroeder  the process doesn't require for someone to have internet connection. The report is goes to the sent monthly. The issue is that the Job is taking time to kick in hence why you are still able to see the report on the draft Report. After some time i you check it will have disappeared. I work on making sure that the job kicks in immediately. 

For CANCEL I will look into it

**Comment by msschroeder** [comment]
lgtm
